title: Ecenaz Jen Ozmen 
logo: "/images/IMG_1009.JPG?raw=true" 
description: >
  I am a senior studying Computer Science with a concentration in Philosophy at Columbia University, I'm also a research assistant at the Columbia Computational Design Lab.
  <br><br>
  <a href="https://www.linkedin.com/in/ecenazozmen/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 
