title: Ecenaz "Jen" Ozmen 
logo: "/images/IMG_1009.JPG?raw=true" 
# pic : "/images/"
description: >
  I am a senior studying Computer Science with a concentration in Philosophy at Columbia University, I'm also a research assistant at the Columbia Computational Design Lab.
  <br><br>
  Interests: windsurfing, longboarding, philosophy, science communication, learning new languages
  <br><br>
  <a href="https://www.linkedin.com/in/ecenaz-ozmen/">Visit My LinkedIn Profile</a> 
  <br><br>
  <a href="https://eozmen410.github.io/pdf/EcenazOzmen_resume08_20.pdf">See My Resume</a>
  <br><br>
  <a href="{{ site.github.owner_url }}">View My GitHub Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 
